### ISSUE TITLE
Callbacks and filters in a multi-user dash app

### ISSUE THREAD

**Issue by Valentine-pl** [seanmajorpayne/dash_multi_user_authentication#5]
Hello,
In your dash app, you use an object in the return of data load() function. So it is possible to use callbacks and filters in a multi-user dash app?
Thanks !!
![image](https://user-images.githubusercontent.com/64286396/140187773-b1258435-66dd-412a-83d9-b35f7c978c64.png)

**Comment by seanmajorpayne** [comment]
Yes there should be no issue using callbacks or filters.
